#!/bin/sh

cat <<EOF > /etc/.env
VITE_API_BASEURL=$VITE_API_BASEURL
VITE_AUTH_API_BASEURL_EXTERNAL=$VITE_AUTH_API_BASEURL_EXTERNAL
VITE_USER_API_BASEURL_EXTERNAL=$VITE_USER_API_BASEURL_EXTERNAL
VITE_GOOGLE_CALLBACK_URI=$VITE_GOOGLE_CALLBACK_URI
VITE_AVATAR_FOLDER=$VITE_AVATAR_FOLDER
EOF
